/** Planet Coaster ride and coaster types, offered as autocomplete suggestions for theme parks. */
export const RIDE_TYPES = [
  'Wooden coaster',
  'Steel coaster',
  'Inverted coaster',
  'Wing coaster',
  'Flying coaster',
  'Hyper coaster',
  'Dive coaster',
  'Launched coaster',
  'Spinning coaster',
  'Mine train',
  'Wild mouse',
  'Bobsled coaster',
  'Junior coaster',
  'Suspended coaster',
  'Water coaster',
  'Ferris wheel',
  'Carousel',
  'Drop tower',
  'Swing ride',
  'Pirate ship',
  'Teacups',
  'Bumper cars',
  'Pendulum ride',
  'Top spin',
  'Observation tower',
  'Log flume',
  'River rapids',
  'Splash boats',
  'Dark ride',
  'Haunted house',
  'Go-karts',
  'Monorail',
  'Park train',
  'Chairlift',
  'Food court',
  'Gift shop',
  'Restaurant',
  'Arcade',
].sort();
