/** Planet Zoo species, offered as autocomplete suggestions in the habitat editor. */
export const SPECIES = [
  'Aardvark',
  'Aldabra Giant Tortoise',
  'Amur Leopard',
  'Arctic Wolf',
  'Babirusa',
  'Bactrian Camel',
  "Baird's Tapir",
  'Bengal Tiger',
  'Black Wildebeest',
  'Bonobo',
  'Bornean Orangutan',
  'Brazilian Porcupine',
  'Cassowary',
  'Cheetah',
  'Chinese Pangolin',
  'Common Chimpanzee',
  'Common Ostrich',
  'Common Warthog',
  'Dall Sheep',
  'Dingo',
  'Dromedary Camel',
  'Eastern Brown Pelican',
  'Formosan Black Bear',
  'Galapagos Giant Tortoise',
  'Gemsbok',
  'Giant Anteater',
  'Giant Panda',
  'Gharial',
  'Grizzly Bear',
  'Hippopotamus',
  'Himalayan Brown Bear',
  'Indian Elephant',
  'Indian Peafowl',
  'Japanese Macaque',
  'Jaguar',
  'Komodo Dragon',
  'Llama',
  'Malayan Tapir',
  'Mandrill',
  'Moose',
  'Nile Monitor',
  'Okapi',
  'Plains Zebra',
  'Polar Bear',
  'Proboscis Monkey',
  'Pronghorn Antelope',
  'Red Kangaroo',
  'Red Panda',
  'Reticulated Giraffe',
  'Ring-tailed Lemur',
  'Saltwater Crocodile',
  'Siberian Tiger',
  'Snow Leopard',
  'Spotted Hyena',
  'Sumatran Tiger',
  'Timber Wolf',
  'West African Lion',
  'Western Lowland Gorilla',
  'White Rhinoceros',
  'African Savannah Elephant',
  'American Bison',
  'Asian Water Buffalo',
  'Bongo',
  'Greater Flamingo',
  "Grevy's Zebra",
  'Koala',
  'Nyala',
  'Red Ruffed Lemur',
  'Siamang',
  'Spectacled Bear',
  'Sun Bear',
  "Thomson's Gazelle",
].sort();
