/**
 * Builds src/styles/tokens.css from the design tokens in design/tokens/*.json.
 * The JSON uses the W3C design-token format, so it can be synced with Figma
 * (variables import/export, or the Tokens Studio plugin) — see design/README.md.
 *
 * Usage: npm run tokens   (also runs before `npm run dev` and `npm run build`)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const TOKENS_CSS = path.join(root, 'src/styles/tokens.css');

type TokenType = 'color' | 'dimension' | 'fontFamily' | 'shadow';
interface ShadowLayer {
  color: string;
  offsetX: string;
  offsetY: string;
  blur: string;
  spread: string;
}
interface Token {
  $value: unknown;
  $type?: TokenType;
}
type Group = { $type?: TokenType } & { [key: string]: unknown };

const read = (file: string) => JSON.parse(readFileSync(path.join(root, 'design/tokens', file), 'utf8')) as Record<string, unknown>;

function formatValue(type: TokenType | undefined, value: unknown, name: string): string {
  switch (type) {
    case 'color':
    case 'dimension':
      if (typeof value !== 'string') throw new Error(`${name}: expected a string`);
      return value;
    case 'fontFamily': {
      const families = Array.isArray(value) ? value : [value];
      return families.map((f) => (/^[\w-]+$/.test(String(f)) ? String(f) : `'${f}'`)).join(', ');
    }
    case 'shadow': {
      const layers = (Array.isArray(value) ? value : [value]) as ShadowLayer[];
      return layers.map((l) => `${l.offsetX} ${l.offsetY} ${l.blur} ${l.spread} ${l.color}`).join(', ');
    }
    default:
      throw new Error(`${name}: unknown token type ${String(type)}`);
  }
}

/** Flattens a token file into [css variable name, value] pairs. Names are the token's path below its top-level group. */
export function flatten(file: Record<string, unknown>): [string, string][] {
  const out: [string, string][] = [];
  const walk = (node: Group, trail: string[], type: TokenType | undefined) => {
    const groupType = (node.$type as TokenType | undefined) ?? type;
    for (const [key, child] of Object.entries(node)) {
      if (key.startsWith('$') || typeof child !== 'object' || child === null) continue;
      const nextTrail = [...trail, key];
      if ('$value' in child) {
        const token = child as Token;
        const name = nextTrail.slice(1).join('-');
        out.push([`--${name}`, formatValue(token.$type ?? groupType, token.$value, name)]);
      } else walk(child as Group, nextTrail, groupType);
    }
  };
  walk(file as Group, [], undefined);
  return out;
}

const block = (pairs: [string, string][], indent: string) => pairs.map(([k, v]) => `${indent}${k}: ${v};`).join('\n');

export function buildTokensCss(): string {
  const base = flatten(read('base.json'));
  const light = flatten(read('theme.light.json'));
  const dark = flatten(read('theme.dark.json'));
  const lightNames = light.map(([k]) => k).join(',');
  const darkNames = dark.map(([k]) => k).join(',');
  if (lightNames !== darkNames) throw new Error('theme.light.json and theme.dark.json must define the same tokens in the same order');

  return `/* Generated by \`npm run tokens\` from design/tokens/*.json — edit those (or sync them from Figma), not this file. */
:root {
${block(base, '  ')}

${block(light, '  ')}
  color-scheme: light;
}

/* Dark theme: follows the system unless someone picked a theme (data-theme on <html>). */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${block(dark, '    ')}
    color-scheme: dark;
  }
}

:root[data-theme='dark'] {
${block(dark, '  ')}
  color-scheme: dark;
}
`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  writeFileSync(TOKENS_CSS, buildTokensCss());
  console.log(`Wrote ${path.relative(root, TOKENS_CSS)}`);
}
